version: "3.9"

services:
  db:
    image: postgres:15
    container_name: ride_service_db
    restart: always
    environment:
      POSTGRES_USER: rideuser
      POSTGRES_PASSWORD: ridepass
      POSTGRES_DB: ride_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
